name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv pip install -e .[dev]
        
    - name: Run lint checks
      run: poe lint_check
      
    - name: Run format checks
      run: poe lint_format
      
    - name: Check lock file
      run: poe lock_check
      
    - name: Generate code
      run: poe generate_code
      
    - name: Check documentation
      run: poe check_doc
      
    - name: Run tests
      run: poe test
      
    - name: Run type checks
      run: poe type_check
